### ISSUE TITLE
Definitely Typed module

### ISSUE THREAD

**Issue by jeswr** [Densaugeo/JSON-String-Splitter#2]
@Densaugeo Thanks for the package. I'm using it in a TS project so I have created type definitions for this in definitely typed (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54263). Would you mind reviewing the PR / being an owner of the type definitions.

**Comment by jeswr** [comment]
Nvm it's been merged

**Comment by Densaugeo** [comment]
Neat, thanks! I haven't used TS but it's nice to see people using this.

I don't expect to make any updates to it, so you likely won't need to do any maintenance.
